name: kitchen-tests

on: [push, workflow_dispatch]

jobs:
  docker:
    if: "!contains(github.event.commits[0].message, '[skip docker]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          # inline YAML or path to separate file (e.g.: .github/filters.yaml)
          filters: |
            all:
              - '.github/workflows/kitchen-tests.yml'
              - 'Dockerfile'
              - 'Gemfile*'
      - name: Build and Push to Docker Hub
        if: steps.filter.outputs.all == 'true'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: brownccv/kitchen-terraform
          tags: infoblox-record-a
  test:
    needs: [docker]
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: self-hosted
    container: brownccv/kitchen-terraform:infoblox-record-a
    steps:
    - uses: actions/checkout@v1
      with:
        clean: false
    - name: Run Kitchen
      run: kitchen test
      env:
        TF_VAR_infoblox_username: ${{ secrets.INFOBLOX_JHUB_USER }}
        TF_VAR_infoblox_password: ${{ secrets.INFOBLOX_JHUB_PSWD }}

