name: terraform-tests

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-tests:
    runs-on: self-hosted
    container:
      image: ghcr.io/brownuniversity/terraform-infoblox-record-a:latest
    steps:
    - uses: actions/checkout@v4
    - name: Run terraform test
      run: |
        terraform init
        terraform test
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
          terraform_version: 1.9.2
      env:
        INFOBLOX_HOST: ${{ secrets.INFOBLOX_JHUB_HOST }}
        INFOBLOX_USERNAME: ${{ secrets.INFOBLOX_JHUB_USER }}
        INFOBLOX_PASSWORD: ${{ secrets.INFOBLOX_JHUB_PSWD }}